version: 2
defaults: &defaults
  working_directory: ~/projects/distributejs/http-check
  docker:
    - image: circleci/node:12.4.0
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - persist_to_workspace:
          root: ~/projects/distributejs/http-check
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/projects/distributejs/http-check/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/projects/distributejs/http-check/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public
workflows:
  version: 2
  test-and-publish:
    jobs:
    - test
    - publish:
        requires:
          - test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
